MAINNET = "mainnet"
TESTNET = "testnet"

TINYLOCK_ASA_MAINNET = 410703201
TINYLOCK_ASA_TESTNET = 47355102

TINYLOCK_APP_MAINNET = 445602322
TINYLOCK_APP_TESTNET = 47355461

ALGOD_ADDRESS = ""

ALGOD_ADDRESS_MAINNET = "https://algoexplorerapi.io"
ALGOD_ADDRESS_TESTNET = "https://testnet.algoexplorerapi.io"

ALGOD_TOKEN = ""

USER_MNEMONIC = ""
